name: Next.js Compatibility

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Run on PRs targeting any branch

jobs:
  # Test compatibility with different Next.js versions
  compatibility:
    runs-on: ubuntu-latest
    name: Next.js ${{ matrix.next }} Compatibility
    
    strategy:
      matrix:
        next: ['13.4.0', '14.0.0', '15.0.0']
      fail-fast: false  # Continue with other jobs if one fails
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    # Create custom cache with explicit key
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: nextjs-compat-${{ runner.os }}-next${{ matrix.next }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          nextjs-compat-${{ runner.os }}-next${{ matrix.next }}-
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build
      
    - name: Run compatibility test for Next.js ${{ matrix.next }}
      run: npm run test:compatibility -- --version=${{ matrix.next }}
      timeout-minutes: 10