name: Tests

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Run on PRs targeting any branch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }} Test

    strategy:
      matrix:
        node: [18, 20]
      fail-fast: false  # Continue with other jobs if one fails

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
      env:
        # Set a unique cache path for each Node version
        npm_config_cache: ~/.npm-cache-${{ matrix.node }}
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build
      
    - name: Run tests
      run: npm test