name: Tests

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Run on PRs targeting any branch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }} Test

    strategy:
      matrix:
        node: [18, 20]
      fail-fast: false  # Continue with other jobs if one fails

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        
    # Use simpler unique cache keys to avoid conflicts
    - name: Cache node modules
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ matrix.node }}-
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build
      
    - name: Run tests
      run: npm test